== La Salvación por medio de Cristo

Un Extracto del Diario de Thomas Story

Comienzo con el propósito de Dios en cuanto a la creación del hombre.
Cuando fue perfeccionado como hombre, Dios sopló en él aliento de vida desde Sí Mismo;
por el cual el hombre se volvió espiritual, vivo en Dios que es espíritu,
semejante a Dios en su mente u hombre interior,
la imagen de Aquel que lo creó en la justicia y santidad de la verdad.
En este estado, Dios le dio al hombre un mandamiento positivo, no de acción,
sino de abstinencia, conectando la muerte y la desobediencia.

El hombre, en el principio, por medio de la voz de Dios,
conocía el mandamiento de Dios y su deber para con Él,
y por un tiempo creyó en la Palabra de Dios (cuya Palabra es la Verdad divina,
eterna y esencial).
Mientras el hombre caminaba en la fe de la Palabra,
vivía en la luz y en la vida divina de ella,
y permanecía y se mantenía en la imagen moral de Dios--justo, santo, incorrupto y puro.

Pero cuando la mente del hombre, a través de la tentación,
dejó de creer en la Palabra de Dios, en la que había creído al principio,
y se adhirió a otra voz (que era falsa y mentira),
se corrompió y se hizo incapaz de seguir disfrutando de la vida
y de la luz de la Palabra--de acuerdo a la promesa de Dios,
que dice: "`el día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:17]
Así, la caída del hombre fue su separación de la vida
y luz divina de la Palabra eterna de Dios,
Su sabiduría y poder;
y la redención del hombre es su restauración (y más
que una restauración) al conocimiento de ella,
estando nuevamente unido a ella.+++[++++++[+++_goback]]

Y puesto que el amor, misericordia y compasión de Dios todavía eran hacia el hombre,
le dio una promesa con la misma Palabra:
"`que la Simiente de la mujer herirá la cabeza de la serpiente,`"^
footnote:[Génesis 3:15]
--ese espíritu sutil que la había traicionado--de modo que,
en el cumplimiento del tiempo, la mujer sería un instrumento en la restauración;
lo cual se cumplió misericordiosamente al pie de la letra.
Porque cuando el ángel de Dios fue enviado a María, la santa virgen, dijo, "`¡Salve,
muy favorecida!
El Señor es contigo; bendita tú entre las mujeres.
Y ahora, concebirás en tu vientre, y darás a luz un Hijo,
y llamarás su nombre JESÚS. Este será grande, y será llamado Hijo del Altísimo;
y el Señor Dios le dará el trono de David su padre;
y reinará sobre la casa de Jacob para siempre, y su reino no tendrá fin.`"^
footnote:[Lucas 1:28-33]

Pero María al principio no le creyó al ángel, y el ángel le respondió,
"`El Espíritu Santo vendrá sobre ti, y el poder del Altísimo te cubrirá con su sombra;
por lo cual también el Santo Ser que nacerá, será llamado Hijo de Dios.
Y María dijo: '`He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.
Y el ángel se fue de su presencia.`'`"^
footnote:[Lucas 1:34-35, 38.]

Y para que toda la humanidad supiera con certeza, en el cumplimiento del tiempo,
quién es esta Persona sagrada, y cuál es la manera de Su venida y aparición,
tanto para los Judíos como a los Gentiles, primero tenía que manifestarse a los Judíos,
bajo el nombre y persona de Jesús, un Salvador; y siendo ungido por Dios,
con toda la plenitud de la Deidad, es por eso que es llamado Cristo;
y bajo ambos títulos, es llamado Jesucristo,
"`el ungido Salvador,`" propuesto como el objeto de la fe de todas las naciones:
Primero a los judíos en la carne, como nacido de la Virgen; y segundo, a los gentiles,
como "`la luz verdadera, que alumbra todo hombre que viene al mundo.`"^
footnote:[Juan 1:9 RV1602 Purificada]

Ahora consideren: 1ro--El testimonio del buen viejo Simeón acerca de Él,
por medio del Espíritu Santo, de que Él es "`Luz para traer revelación a los gentiles,`"^
footnote:[Lucas 2:32]
y en ese sentido, es su luz y salvación,
de acuerdo a la promesa del pacto de Dios mencionada anteriormente.

2do--La evidencia de Juan, donde habla plena y claramente, diciendo:
"`En el principio era la Palabra, y la Palabra era con Dios, y la Palabra era Dios.
En Él estaba la vida, y la vida era la luz de los hombres.
Aquél era la Luz verdadera, que alumbra a todo hombre que viene en este mundo.
La Palabra fue hecha (o tomó forma de) carne, y habitó entre nosotros (y vimos su gloria,
gloria como del unigénito del Padre), lleno de gracia y de verdad.`"^
footnote:[Juan 1:1, 4, 9, 14]

3ro; El testimonio de Cristo Mismo, donde dice: "`Yo soy la luz del mundo;
el que Me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.`"^
footnote:[Juan 8:12]
De nuevo, "`Jesús les dijo: Aún por un poco está la luz entre vosotros;
andad entre tanto que tenéis luz, para que no os sorprendan las tinieblas;
porque el que anda en tinieblas, no sabe a dónde va.`"^
footnote:[Juan 12:35]
"`Entre tanto que tenéis la luz, creed en la luz, para que seáis hijos de luz.`"^
footnote:[Juan 12:36]

Y puesto que el Padre ha prometido y ofrecido a Su Hijo, y puesto que Él es esa Luz,
como también el nuevo y eterno pacto con la humanidad
para su restauración y establecimiento (no de obras,
sino de vida); así ahora, quien quiera entrar en este pacto con Dios,
primero debe creer en Aquel a quien Dios ha enviado,
y en la forma y manera en la que lo ha enviado, según Sus promesas.

Ahora bien, un pacto no es de una sola parte, sino de dos por lo menos.
Por lo tanto Dios, quien es amor eterno y divino, infinito en bondad y misericordia,
le place de Su propia naturaleza y amor a la humanidad, enviar de este modo a Su Hijo,
el Señor Jesucristo, al mundo,
quien mediante una muerte voluntaria sobre el madero de la cruz,
según el determinado consejo y propósito del Padre,
declaró Su misericordia y Su perdón gratuito de los pecados del mundo entero,
bajo condiciones que eran adecuadas para el estado,
razón y entendimiento de la humanidad: es decir,
bajo la fe en Dios el Padre de todos y en Jesucristo el Hijo de Dios,
y el arrepentimiento de las obras muertas.
Estos son los términos razonables y necesarios que se requieren
de la humanidad en nuestra parte de este pacto,
con el fin de que podamos ser restaurados al verdadero conocimiento de Dios,
y ser hechos capaces de estar unidos a Dios,
a través de Cristo el Mediador entre Dios y los hombres en este pacto;
porque es por y a través de Él que entramos a este pacto,
y que permanecemos firmes e inconmovibles en el mismo para siempre.

Por lo tanto,
debemos recibir al Salvador de la manera en que Él es enviado y ofrecido a nosotros;
no solo como se nos ofrece en la cruz para la expiación de los pecados pasados,
sino también como la Luz divina, alumbrando nuestros corazones y entendimientos,
como lo indica el mismo Cristo, cuando dice, "`Entre tanto que tenéis la luz,
creed en la luz, para que seáis hijos de luz`"^
footnote:[Juan 12:36]
--es decir, hijos de Dios, que es esa luz.
De modo que, así como Adán cayó del conocimiento verdadero de Dios,
y de un sentido de Su divino amor, presencia, bondad, y otros atributos,
por incredulidad; asimismo nosotros, su posteridad según la carne,
podemos todos levantarnos y ser restaurados por la fe en Cristo, el segundo Adán,
el Señor del cielo, el Espíritu vivificante.
Esta restauración no es para la vida animal, que ya tenemos por naturaleza,
y en la cual estamos en enemistad con Dios y con todos Sus caminos,
sino para la vida eterna, para que todos sepamos lo que esa Palabra significa:
"`Así como en Adán todos mueren, también en Cristo todos serán vivificados.`"^
footnote:[1 Corintios 15:22]
Y, "`Así que,
de la manera que por el delito de uno vino la culpa a todos los hombres para condenación,
así por la justicia de uno vino la gracia a todos
los hombres para justificación de vida.`"^
footnote:[Romanos 5:18 RV1602 Purificada]

De nuevo,
las Sagradas Escrituras nos han dado una descripción o explicación
clara sobre la operación de esta luz divina,
por la cual podemos identificarla (incluso como hombres naturales) por sus efectos;
porque el evangelista dice que el Consolador, que es el Espíritu Santo,
el Espíritu de Cristo, quien es esa luz, "`cuando Él venga,
convencerá al mundo de pecado, de justicia y de juicio.`"^
footnote:[Juan 16:8]
Y el apóstol dice, "`todas las cosas que son redargüidas,
son hechas manifiestas por la luz; porque la luz es lo que manifiesta todo.`"^
footnote:[Efesios 5:13 RV1602 Purificada]
De nuevo, "`Esta es la condenación (del mundo): que la luz (sí, esta Luz) vino al mundo,
y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas.`"

Este es Él, esa Luz divina y eterna,
de quién Juan el Bautista y los apóstoles de Cristo dieron testimonio;
y especialmente el apóstol Pablo, que fue enviado por Cristo a los Gentiles,
"`para abrir sus ojos,
para convertirlos de las tinieblas a la luz (incluso a Él quien es esa Luz),
y de la potestad de Satanás a Dios;`"^
footnote:[Hechos 26:18]
para que siendo convertidos,
"`puedan recibir perdón de pecados y herencia entre los santificados por la Fe en Él,
el Señor.`"^
footnote:[Hechos 26:18]
