== Selección del Diario de Thomas Story

Creo apropiado hacer un recuento en este lugar,
de algunos de los tratos misericordiosos del Señor conmigo desde mis primeros
días. Yo no era naturalmente adicto a mucho vicio o maldad,
y sin embargo, a través de la conducta de muchachos rudos en la escuela, había adquirido,
por imitación, algunas cosas que tendían a esa dirección. No obstante,
cuando ponía esas cosas en práctica, ya fuera de palabra o de hecho,
en esos momentos encontraba en mí algo,
que repentinamente me sorprendía con una consciencia de maldad,
y que me avergonzaba cuando estaba solo,
a pesar de que lo que había dicho o hecho no era malo en
la opinión común de aquellos con quienes conversaba,
o entre los hombres en general.
Y aunque no conocía ni entendía qué era eso que me reprobaba,
aun así tenía tanta influencia y poder en mí,
que fui considerablemente reformado de esos hábitos, los que con el tiempo,
podrían haber sido el fundamento de males mayores y vicios más graves.

Sin embargo, conforme maduraba, tenía muchos altibajos en mi mente,
y las tentaciones comunes entre los jóvenes se me presentaban con frecuencia y con fuerza.
Y aunque era preservado de la culpa a la vista de los hombres,
no era así delante del Señor, que ve en lo secreto,
y que en todo momento contempla todos los pensamientos, deseos,
obras y actos de los hijos de los hombres, en todas las edades y en todo el mundo.
Los deseos de la carne,
los deseos de los ojos y la vanagloria de la vida presentaban sus
objetos delante de mí. Los aires de juventud eran muchos y potentes,
y no faltaban la fuerza, actividad y buena apariencia.
Además,
descubrí que una capacidad mental natural y sus muchas
adquisiciones no estaban fueran de mi alcance,
por lo que la gloria,
avance y ascenso del mundo fueron esparcidos como redes ante mi vista,
y su amistad empezó a dirigirse a mí con un adulador cortejo.

Yo llevaba una espada, el uso de la cual entendía bien,
y había frustrado a varios maestros de esa disciplina en el norte y en Londres.
También cabalgaba con armas de fuego, y conocía el uso de ellas,
aunque no era naturalmente pendenciero.
Yo me había impuesto la siguiente regla:
Nunca ofender o afrentar a nadie voluntariamente o con intención.
Pero si yo inadvertidamente hubiera ofendido a alguien,
habría preferido admitir mi error que mantener o vindicar algo incorrecto;
y habría asumido el mal comportamiento de otros y no me habría ofendido
donde no había habido ninguna ofensa voluntariamente intencionada.
Pero también estaba preparado para castigar una afrenta o un agravio personal,
cuando era hecho en desprecio o con intención. Sin embargo, nunca me topé con tal suceso,
salvo una vez, y luego mantuve mis propias máximas con éxito,
para no herir ni ser herido.
La buena providencia del Todopoderoso siempre estuvo sobre mí,
y conocía bien mi intención en toda mi conducta.

Pero con el paso del tiempo,
cuando los movimientos de corrupción y pecado se hicieron cada vez más fuertes en mí,
el Señor, en Su gran bondad y misericordia,
puso de manifiesto en mi entendimiento la naturaleza y fin de ellos.
Y entonces,
al tener una visión de ellos en la verdadera luz y del peligro que los acompañaba,
se hicieron extremadamente pesados y agobiantes para mi mente.
Entonces me sentí profundamente convencido de la necesidad de la gran obra de la regeneración,
pero yo no tenía la experiencia ni la evidencia de que esta hubiera sido
hecha en mí. Esta comprensión me sorprendió enormemente con temor,
al considerar la gran incertidumbre en la continuación de la vida natural,
y empezó a poner una vileza secreta sobre el mundo,
su gloria y sobre todo lo que yo tenía para gloriarme.
Yo guardé estos pensamientos dentro de mi propio pecho,
al no conocer ningún alma a quien yo pudiera con seriedad y seguridad divulgárselos.
De hecho, por un considerable tiempo,
nadie discernió por alguna apariencia externa mi preocupación interna,
lo que era muy ventajoso y seguro para mí, como descubrí después.

Es admirable los diversos pasos por los que el Señor se complace
sacar el alma del hombre fuera de este mundo y de su espíritu,
y dirigirla hacia Sí mismo.
Sin embargo, estoy inclinado a pensar, que en Su divina e ilimitada sabiduría,
Él no sigue el mismo método externo ni los mismos pasos con todos,
sino que varía la obra de Su providencia,
según se adapten y soporten mejor los estados y circunstancias de cada uno.

Un accidente que me sucedió me hizo considerar aún más mis caminos,
la incertidumbre de la vida, mi presente estado y el fin último.
Sucedió así: Mientras cabalgaba suavemente con un conocido,
camino a una iglesia de campo, mi caballo se tropezó, cayó y se quebró el cuello,
y quedó recostado tan pesadamente sobre mi pierna, que no podía sacarla de debajo de él;
sin embargo, yo no recibí ningún daño. Entonces, mientras permanecía junto a él pensé,
que mi propia vida pudo haberse acabado por ese motivo,
y que yo no me encontraba en una condición adecuada para el cielo,
al no tener aún evidencia de esa necesaria obra de regeneración.
Esto trajo una gran pesadez sobre mi mente,
la cual no se apartó totalmente, hasta que a través de la infinita misericordia de Dios,
fui favorecido con más conocimiento y un mejor estado.

Hasta ese momento, yo había conocido la gracia de Dios en mí,
sólo como una '`manifestadora`' del mal y del pecado, como una palabra de reprensión,
y como una ley que condenaba y juzgaba aquellos pensamientos, deseos, palabras, pasiones,
afectos, actos y omisiones,
que están asentados en la primera naturaleza y arraigados en la mente carnal,
donde las sugerencias, tentaciones e influencias del maligno obran y prevalecen.
Por esta divina gracia fui, en un buen grado, iluminado,
reformado y habilitado para rehuir y abstenerme de
todas las palabras y actos conocidos como malos,
y experimenté la justicia moral restaurada en medida en mi mente,
y así engendrada en mí. Entonces fui destetado de todos mis antiguos conocidos y compañías.
Aunque sus modales y conversaciones no eran viciosos (ya que esto nunca me gustó),
llegaron a ser gravosas y desagradables para mí,
porque vi que ellos no tenían el conocimiento de Dios,
ni la conducta que yo quería. Sin embargo,
yo todavía no conocía la divina gracia en su propia naturaleza, tal como está en Cristo,
es decir, como una Palabra de fe, santificación, justificación, consolación y redención,
pues aún estaba vivo en mi propia naturaleza.
El Hijo de Dios no había sido revelado en mí todavía, ni yo,
por el poder de Su santa cruz, había sido crucificado, ni muerto;
estando aún sin el conocimiento de la sustancia de la verdad,
y en un estado contrario a Él y no reconciliado.

Pero el Señor no me dejó ahí. En Su incomparable misericordia,
me siguió con Sus santas amonestaciones,
e inclinó cada vez más mi mente hacia un seria indagación
de Él y de Su propia verdad y Palabra.
No conocía a nadie en toda la tierra que hubiera podido enseñarme estas cosas,
pues el mundo (según juzgué, por los caminos y cursos generales de los hombres,
de todas las formas y condiciones) parecía universal y totalmente ignorante del Señor,
teniendo sólo unos indicios históricos y tradicionales
sobre Él y sobre Su doctrina y caminos.
Tal conocimiento parecía tener poco o ningún efecto
o influencia sobre las mentes y vidas de los hombres,
y más bien era una especie de conocimiento o imagen muerta, y por tanto,
el hombre (estando muerto mientras aún vivía) no creía en el verdadero Dios,
real y salvadoramente, ni en Jesucristo,
aunque hicieran profesión y hablaran mucho de ellos.
Yo no sabía entonces,
que el Señor tenía un pueblo en el mundo que era reconocido
como Su propio rebaño y familia por Su presencia entre ellos.

Al estar mi mente en verdad anhelante de Dios,
sedienta hasta la muerte del conocimiento del camino de vida,
le plació a Dios oír la voz de mi necesidad, pues yo necesitaba la salvación ya,
y el Señor sabía que mi caso no podía admitir más demora.
Moviéndose en Su propia y libre misericordia y bondad, o sea,
en el mismo amor en el que envió a Su amado Hijo
al mundo para buscar y salvar a los perdidos,
por la tarde del primer día del segundo mes del año 1689, estando solo en mi aposento,
el Señor irrumpió sobre mí inesperadamente, tan rápido como un rayo desde los cielos,
y como un Juez justo, todopoderoso, omnisciente y condenador de pecado.
Delante de Él, mi alma, como en la más profunda agonía, temblaba,
estaba confundida y asombrada, y llena de un temor tan terrible,
que no hay palabra que alcance o que lo pueda explicar.
Mi mente parecía sumida en absoluta oscuridad,
y la eterna condenación parecía encerrarme por todo
lado (como en el centro de un horrible hoyo),
para que no viera la redención desde ahí,
ni el misericordioso rostro de Aquel que yo había buscado con toda mi alma.
Pero en medio de esta confusión y espanto, donde ningún pensamiento podía ser formado,
ni se podía retener ninguna idea además de la muerte eterna que poseía a todo mi hombre,
una voz se formó y pronunció en mí: "`Sea hecha Tu voluntad, oh, Dios.
Si esta es obra Tuya y no mía, te entrego mi alma.`"
Al concebir estas palabras procedentes de la Palabra de Vida, rápidamente encontré alivio.
Había una virtud sanadora en ellas, y el efecto fue tan veloz y poderoso,
que en un instante todos mis temores se desvanecieron como si nunca hubieran existido,
y mi mente quedó tan calmada,
quieta e inocente como la de un niño pequeño. El Día del
Señor amaneció y el Sol de Justicia se levantó en mí,
con sanidad divina y virtud restauradora en Su rostro; y así,
Él se convirtió en el centro de mi mente.

En esta maravillosa operación del poder del Señor,
denunciando juicio con tierna misericordia y en la
hora de mi más profunda preocupación y prueba,
perdí mi viejo yo y llegué al principio del conocimiento de Él, del Justo y Santo,
a quien mi alma había anhelado.
Ahora veía la totalidad del cuerpo de pecado condenado en mi propia carne,
no en actos específicos,
como si sólo viajara por el camino que lleva a un estado de moral perfecta,
sino por un solo golpe y sentencia del gran Juez de los vivos y muertos.
Por medio de este golpe toda la mente carnal, con todo lo que moraba en ella, fue herida,
y la muerte empezó en el amor al yo, el orgullo, los malos pensamiento y todo deseo malo,
con toda la corrupción del primer estado y de la vida natural.
Aquí tuve una degustación y perspectiva de la agonía del Hijo de Dios,
de Su muerte y estado sobre la cruz,
cuando el peso de los pecados de toda la humanidad estaba sobre Él,
y cuando '`pisó solo el lagar y no había nadie que lo asistiera`' (Isaías
63:3). Entonces todos mis pecados pasados fueron perdonados y eliminados,
y mi propio '`querer y correr,`'^
footnote:[Romanos 9:16]
con los afanes y luchas terminaron.
Todos mis razonamientos y conceptos carnales acerca del conocimiento de Dios y de los
misterios de la religión (que yo veía que no eran más que naturales) terminaron;
aunque ellos habían ejercitado por mucho tiempo mi mente tanto de día como de noche,
y habían quitado mi deseo de comida y reposo natural.
Entonces mis penas finalizaron y mis ansiosas preocupaciones fueron quitadas,
y en su lugar se levantó un verdadero temor,
el cual encontré ser el inicio a la sabiduría, donde descubrí el verdadero Sábado;
el descanso santo, celestial, divino y libre, y el más dulce reposo.
Cuando terminó este profundo ejercicio, dormí hasta la mañana siguiente,
y tuve un mayor y mejor refrescamiento y consuelo,
de los que había sentido durante las últimas semanas.

Al día siguiente descubrí mi mente tranquila y libre de ansiedad,
en un estado como el de un niño pequeño. Permanecí en esta condición hasta la noche,
y aproximadamente a la misma hora de la tarde cuando
había venido sobre mí la visitación anterior,
toda mi naturaleza y ser, tanto la mente como el cuerpo,
fueron llenados de la divina presencia como nunca antes había experimentado,
ni había pensado que se podía experimentar.
De seguro, nadie puede formarse la menor idea de tal cosa, aparte de la que da el Santo.
La divina Verdad ahora era evidente; no faltaba nada más para probarla.
Yo no necesitaba razonar acerca de Él,
porque todo fue sustituido por una divina y verdaderamente
maravillosa evidencia y luz que procedían sólo de Él,
que no dejaban lugar para la duda ni para ninguna pregunta.
Porque como el sol, en el firmamento abierto del cielo,
no se descubre ni se ve excepto por su propia luz,
y de esta manera la mente del hombre determina las
cosas por vista y sin ningún proceso de razonamiento,
así, y más que así, por la prominente influencia y divina virtud del Altísimo,
mi alma estaba segura de que era el Señor. Lo vi a Él en Su propia luz,
por ese bendito y santo medio que desde antes había
prometido dar a conocer a todas las naciones,
es decir, por el ojo que Él mismo había formado,
abierto e iluminado mediante la emanación de Su propia gloria eterna.
Y así fui llenado de perfecta consolación,
la cual nada sino la Palabra de Vida puede declarar o dar.
Fue entonces, y no antes, que supe que Dios es amor,
es decir, el amor perfecto que echa fuera todo temor;
y fue entonces que supe que Dios es luz eterna y que en Él "`no hay ningunas tinieblas.`"

También fui altamente favorecido con una visión de la manera
de operar del Todopoderoso al asumir la naturaleza humana,
y vestir Su luz y gloria divina e inaccesible con ella; es decir,
con un alma y una mente inocentes, santas y divinas,
comparables con las de los hijos de los hombres.
Esto era como un velo,
por medio del cual el Altísimo condescendía a la condición baja del hombre,
en quien también el hombre, al ser refinado como oro tratado, y de este modo,
hecho apto para el Santo, puede acercarse a Él por un medio apropiado,
y habitar allí con el Señor y disfrutarlo para siempre.

A partir de ese momento,
yo no deseaba nada más que conocer al Señor y ser
alimentado del pan de vida que sólo Él puede dar,
y que no deja de entregar cada día. Por Su propia voluntad y bondad,
le plació a Él abrir mi entendimiento gradualmente a todos los
misterios principales de Su reino y a las verdades de Su evangelio,
ejercitando mi mente con sueños, visiones, revelaciones, profecías,
descubrimientos divinos y demostraciones.
Y por medio de Su eterna y divina luz, gracia, Espíritu, poder y sabiduría o palabra,
instruyó e informó mi mente,
permitiéndole también a Satanás ministrar tentaciones y profundas pruebas,
para que viera mi propia debilidad y peligro,
y probara hasta lo sumo la fuerza y eficacia de ese divino amor y verdad,
con los que el Señor, en Su infinita bondad y misericordia, había visitado mi alma.

Todas las cosas que veía y oía en Su maravillosa obra de
creación testificaban de Él. Mi propia mente y cuerpo,
los animales, reptiles y vegetales de la tierra y el mar,
sus rangos y subordinación unos a otros,
y todos ellos subordinados a los hijos de los hombres.
El sol, la luna y las estrellas, la innumerable hueste del cielo,
y ese espacio infinito en el que se mueven sin interferir, ni molestarse uno a otro,
todos dependiendo unos de los otros.
Vi que todo esto estaba conectado sin división,
y que era gobernado por inalterables leyes bajo las que la todopoderosa Palabra y Decreto,
que les dio el ser y los formó, los colocó y los estableció. Pero,
como la corona de todo, y el único camino verdadero y seguro,
le plació al Altísimo (por la expresión de Su propia
bondad) revelar en mí al Hijo de Su amor,
es decir, a Su sabiduría y poder, por quien Él diseñó y efectuó todas las cosas.
Entonces fui enseñado a temerle; entonces fui enseñado a amarlo; entonces, y no antes,
mi alma fue, en efecto, correctamente instruida e informada.

Pero estas operaciones secretas estaban confinadas en mi corazón,
de modo que nadie sabía nada de ellas.
Se observaba un cambio en mí, pero no se veía la causa.
Hice a un lado mi habitual ostentación, mis actos y saludos ligeros,
y dejé de lado mi espada (la que había usado, no para herir, ni por miedo al hombre,
sino como adorno elegante y masculino).
Además,
quemé mis instrumentos musicales y me despojé de las partes superfluas de mi vestimenta,
dejando únicamente lo que era necesario o estimado decente.
Dejé de asistir a la adoración pública,
aunque no con la idea de unirme a ninguna otra secta, porque estaba inclinado a concluir,
por lo que había observado, que esas manifestaciones eran exclusivamente mías,
y que no había nadie con quien yo pudiera asociarme apropiadamente.
También fui llevado a creer que un día me vería obligado
a oponerme al mundo en asuntos de religión,
pero cuándo o cómo sucedería, no lo preveía.

Permanecía en un estado quieto y retirado,
y mientras el Libro de la Vida era revelado en mi mente, yo leía lo que el Señor mismo,
por medio del dedo de Su poder, había escrito,
y lo que el León de la tribu de Judá había revelado ahí. Las Escrituras de la Verdad,
escritas por Moisés y los profetas, los evangelistas y los apóstoles de Cristo,
eran traídas a mi memoria todos los días,
incluso cuando no las leía. Estas eran aclaradas
y manifestadas en mi entendimiento y experiencia,
según se relacionaban con mi propio estado y también de manera general;
aunque no codiciaba conocer ningún misterio o cosa contenidas en ellas,
aparte de lo que el Señor, en Su propia y libre voluntad y sabiduría,
pensaba que era adecuado manifestar.
A medida que la naturaleza y virtud de la verdad divina se incrementaban en mi mente,
se forjaba en mí a diario, una mayor conformación a ella por su propio poder,
y reducía mi mente a una sólida quietud y silencio.
Este era un estado más adecuado para prestarle atención a la Palabra divina,
y distinguirla de todos los otros poderes,
y discernir sus influencias divinas de todas las imaginaciones y otros movimientos.
Al ser diariamente alimentado con el fruto del Árbol de la Vida,
yo no deseaba otro conocimiento que ese que me era dado.

En la tarde del 21 del mes once de 1689, se me ordenó silencio (aunque no por mí),
en el que se me obligó a permanecer hasta la noche.
Luego la escritura de Juan 13:10 fue traída a mi memoria,
y comencé a escribir de la siguiente manera, según se me revelaban las cosas en mi mente:

[.embedded-content-document.prayer]
--

"`Jesús le dijo: '`El que está lavado, no necesita sino lavarse los pies,
pues está todo limpio.`'`" El lavado de los pies significa la limpieza de los caminos,
y aquellos que se hayan lavado en la fuente de la regeneración,
caminarán por sendas limpias y producirán fruto en
concordancia con la naturaleza del Árbol de la Vida.
Estos caminarán en fe, amor, obediencia, paz, santidad, justicia, juicio,
misericordia y verdad.
Y cualquiera que diga que es del Padre y no tiene amor, es mentiroso,
y la Palabra viva no gobierna en él. Porque el que
ha conocido a la Palabra y permanece en ella,
tiene al Padre, porque la Palabra de Verdad da testimonio del Padre;
y el que haya nacido de Dios guardará Sus mandamientos.

¡Oíd, oh montes, y escuchad, oh cedros del Líbano; el Señor, la luz de Jerusalén,
la vida de los santos,
ha puesto una cántico de alabanza en mi boca y me ha alegrado
en el valle de Josafat! ¡Yo estaba en el desierto,
y Él me guió por el poder de Su mano derecha! ¡Yo estaba caído,
y Él extendió Su brazo y me puso de pie! ¡Sí, yo estaba muerto, y he aquí,
Él me levantó de la tumba! ¡Yo estaba hambriento,
y Él me ha alimentado con el pan de Su pacto eterno!
¡Yo caía débilmente desmayado en el camino,
pero el Rey de la montaña santa me revivía por la palabra
de Su promesa! ¡Él ha colocado mis cimientos con belleza,
con piedras preciosas de diversos colores, y la arquitectura es toda gloria!

¡No teman ustedes, los de baja condición,
porque en nuestro Dios no hay acepción de personas! ¡No teman ustedes, pequeños,
porque Él les ha mostrado Su misericordia antigua,
y en Él no hay sombra de variación! ¡Despierten, despierten ustedes,
los que duermen en delitos y pecados,
porque la trompeta suena fuerte en la ciudad de nuestro Rey! ¡Levántense ustedes muertos,
y pónganse de pie delante de Él, porque Él es fiel y verdadero y ha enviado Su Palabra!

¡Conquista, oh, conquista, Tú, santo amor de Dios,
a todos los que en ignorancia se oponen a Tu misericordia!
¡Hiere a Tu pueblo con gran sed,
oh, Señor Dios de misericordia,
para que beban abundantemente de las aguas de Tu salvación! ¡Hazlos tener hambre, oh,
Vida de los justos, para que coman abundantemente,
y sean refrescados por el pan de vida eterna! ¡Llámalos
de las cáscaras de las sombras externas,
y aliméntalos con Tu maná escondido y con el Árbol
de la Vida! ¡Quita de ellos el vino de la tierra,
del que han abusado para abominar,
y dales el fruto de la Vid viva en la mesa del Padre! ¡Lávalos
en la fuente de regeneración por medio de Tu Santo Espíritu,
y límpialos por medio de Tus juicios justos, para que retengan Tu amor!

¡Considera su debilidad, oh, Padre de misericordias, porque ellos son carne y sangre,
y no pueden ver a través del velo,
Tu santa morada! ¡Rasga el velo de la sabiduría carnal en la mente terrenal, Tú,
maravilloso Consolador,
y muestra Tu gloria en su completa perfección! ¡Disuelve el gran mundo de orgullo,
codicia, embriaguez, mentira, maldición, opresión,
comunicaciones inmundas y prostituciones,
y establece la justicia y la paz para siempre!`"

Yo estaba en silencio delante del Señor, como un niño aún no destetado.
Él ponía palabras en mi boca y yo cantaba Su alabanza en audible voz.
Yo llamaba a mi Dios desde gran profundidad,
y Él se vestía con entrañas de misericordia y tenía compasión de mí,
porque Su amor era infinito y Su poder no tenía medida.
Él me pidió mi vida, y yo la ofrecí en el estrado de Sus pies,
pero me la dio '`por botín`' con una añadidura indescriptible.
Él me pidió mi voluntad, y yo la rendí a Su llamado,
pero me devolvió la Suya como señal de Su amor.
Él me pidió el mundo, y yo lo puse a Sus pies, con las coronas de este;
no las retuve ante el llamado de Su mano.
¡Pero presten atención al beneficio del intercambio!
Porque Él me dio en lugar de la tierra, un reino de paz eterna,
y en lugar de las coronas de vanidad, una corona de gloria.
Me miraban, y decían que estaba loco, distraído y que me había vuelto un tonto.
Se lamentaban porque había llegado mi libertad.
Susurraban contra mí en la vanidad de sus imaginaciones,
pero yo inclinaba mi oído a los susurros del Espíritu de Verdad.
Yo decía: "`¿Qué soy yo para recibir tal honor?`"
Sin embargo,
Él removía las montañas de mi camino y mediante Sus
operaciones secretas me empujaba hacia adelante.

--

[.offset]
+++[+++En otro momento él escribió la siguiente oración:]

[.embedded-content-document.prayer]
--

¡Oh, Todopoderoso, incomprensible, e infinitamente misericordioso Señor Dios,
por cuanto nadie puede entrar en Tu reposo, a menos que sea regenerado y renovado,
yo humildemente te ruego, en el nombre y por amor a Tu Hijo Cristo,
que te complazcas en lavarme en el agua de vida, y que purifiques mi alma contaminada,
con el fuego santo de Tu infinito amor!

¡Oh, haz que yo pueda vivir en Ti, y caminar en el camino vivo de verdad, amor, paz,
gozo,justicia, santidad, templanza y paciencia,
mientras Te complaces en mantenerme en este lugar de labranza!

¡Sé mi fortaleza y mi justicia, para que yo no me desvíe de Tus sendas,
por la fragilidad de este tabernáculo terrenal!

¡Dame el pan de vida cada día, el que Tú gratuitamente ofreces al hambriento todo el día!

¡Y dado que nadie puede comer de este pan,
sino aquellos que están hambrientos y sedientos de justicia, dame (oh, Tú,
que eres mi salvación), un ferviente deseo, una fe salvadora, una fe viva,
para aferrarme a Tu más segura promesa,
y poder ser hecho partícipe de la gloria que está reservada,
para Tus siervos en Tus moradas eternas!

--

Al encontrar que la conversación de la humanidad era generalmente trivial,
no digna del pensamiento de criaturas racionales,
y que se inclinaba mucho más al vicio que a la virtud,
y dado que mi mente había sido un poco renovada por la influencia de la verdad divina,
permanecía mucho en silencio y solo.
A veces tenía pensamientos sobre otros objetos,
de los cuales escribía (sin ninguna búsqueda o trabajo)
tal como eran presentados en mi mente de tiempo en tiempo.

[.small-break]
'''

+++[+++La siguiente oración escrita muestra que él también
experimentó disminuciones de la vida divina,
después de las épocas de regocijo de las que ha hablado.]

[.embedded-content-document.prayer]
--

¡Oh, Señor, ten piedad de un alma que perece, llevada bajo una multitud de afectos viles,
pisoteada bajo el pie de la insolencia del maligno!

¡Desmayo bajo el yugo, oh, fiel y verdadero,
y no tengo esperanza sino a Ti! ¡Mi corazón está cansado de suspirar bajo angustias,
y mis dolores se incrementan!

¿Cuándo vendrá mi día? ¿Cuándo veré el sello de mi salvación?

¡Oh, obra en mí la ley de amor eterno,
y fija mis límites ahí por los siglos de los siglos! ¡Tú, que les dijiste a los mundos:
"`Sean acabados,`" y así fue, dile ahora a mi alma: "`¡Sé perfecta!,`" y será hecho!

¡Purifícame, oh, Dios, por medio de los juicios de Tu mano derecha,
y deja que Tus misericordias estén siempre delante de mí! ¡Levántame,
para que yo pueda alabarte en el firmamento de Tu poder! ¡Humíllame,
para que pueda exaltar Tu nombre en medio de las naciones!

--

Una profunda reflexión entró a mi mente con respecto a los
estados de muchas personas en la forma nacional de adoración,
como también entre los numerosos disidentes de ella.
Yo ocasionalmente había oído a algunos de sus predicadores,
particularmente al Dr. Richard Gilpin, de Scaleb Castle, un médico capaz,
y un anciano y famoso predicador entre los presbiterianos,
y había observado a muchos otros que parecían sinceros y tener
buenas intenciones en sus respectivos modos de adoración. Por tanto,
surgió la pregunta en mí si no sería culpa mía,
por falta del verdadero conocimiento de Dios en mí mismo previo a ese momento,
que yo me había visto impedido de disfrutar Su presencia
entre ellos como la disfrutaba entonces,
es decir,
desde que había sido visitado por el Señor y atraído
al retiro por el consuelo de Su presencia secreta.
Basado en esta consideración determiné ir otra vez,
y ver si la buena presencia del Señor se manifestaba en mí ahí,
como se manifestaba cuando estaba solo en mi retiro.

Fui al lugar llamado St. Cuthbert`'s, en la ciudad de Carlisle,
donde usualmente había oraciones y un sermón en la tarde el primer día de la semana,
pero sin la pompa, ruido y espectáculo que acompañaban el servicio en la catedral.
Sentado ahí con mi mente retirada en el interior para esperar
en el Señor (como Él mismo me había enseñado a hacer),
descubrí que el Señor no reconocía su adoración mediante Su palpable presencia,
ni a mí en ese lugar, aunque Él es omnipresente.
En lugar de eso, mi mente se llenó de oscuridad y se abrumó con tal angustia,
que difícilmente iba a poder quedarme hasta que se terminara el tiempo.
Pero para no hacer algo que pudiera considerarse inapropiado, continué hasta el final,
y luego, al regresar a mi aposento en angustia, nunca más volví entre ellos.

Sin embargo,
aunque me abstenía de asistir a toda adoración externa (o eso que era llamado así),
al haber determinado seguir al Señor adondequiera que a Él le placiera guiarme,
descubrí en mi mente el amor,
buena voluntad y compasión universal hacia todo tipo de personas,
fueran protestantes de diferentes denominaciones, romanos, judíos, turcos o paganos.
Sin embargo,
observé que sus varias religiones eran principalmente el resultado de la educación,
tradición o azar.
Porque el que nace y es educado entre los protestantes de alguna secta,
es respectivamente así. El que nace y es educado entre los romanos, es romano.
Y así con todo el resto,
hasta que por alguna circunstancia o interés cambian de una forma a otra;
o a veces (aunque más raramente),
por causa de las convicciones internas del Santo Espíritu de Dios,
obtienen un entendimiento correcto y llegan a adorarlo a Él en verdad.
Por tanto, permanecía quieto y esperaba la guía del Señor,
y la evidencia de Su presencia en cuanto a qué hacer, o dónde permanecer,
aunque los protestantes en general, y especialmente la iglesia nacional,
eran todavía más cercanas para mí que cualquier otra secta.

Así, en general,
el mundo parecía estar muerto (como estatuas caminantes)
con respecto al verdadero conocimiento de Dios,
a pesar de la verdad de algunos conceptos que ellos sostenían
con relación a cuestiones de hecho e interpretación literal.
Yo, en ese entonces,
no me había dado cuenta de que el Señor Dios tenía un cuerpo colectivo de personas,
que en aquel día lo adoraban verdaderamente según Su propia institución;
ni sabía de alguien en la tierra que hubiera sido
enseñado de Dios por medio de Su propia gracia,
y que pudiera comunicarme lo que yo no podía preguntar ni pensar.
Sin embargo, a su debido tiempo descubrí que estaba equivocado en estas cosas,
tal como el profeta de antaño,
que pensaba que había estado solo mientras todo Israel se apartaba del Señor.

En la medida que la vida del Hijo de Dios prevalecía en mí,
yo me volvía más y más inocente, humilde, amoroso y caritativo con los pobres,
a quienes les daba dinero según mi capacidad,
y sin ostentación o expectativa de recompensa.
Creo que podría ser apropiado contar un ejemplo de esto,
ya que estuvo acompañado de algunas circunstancias interesantes.
En el tiempo que el Rey Guillermo III estaba sometiendo Irlanda,
algunas personas y familias huyeron de las inconveniencias
y dificultades de la guerra y llegaron a Inglaterra.
Entre otros, un ministro de la secta '`independientes`' y su joven hijo,
llegaron a la casa de mi padre en Carlisle donde yo vivía entonces,
y al estar en necesidad, pidió ayuda.
Yo le di media corona, lo cual,
al ser más de lo que esperaba o había recibido en otro lugar,
le dio la oportunidad de entablar una conversación sobre algunos puntos
de religión. Él cortésmente me preguntó a qué forma de adoración asistía.
Yo le respondí que anteriormente frecuentaba la adoración nacional,
según mi educación, pero que había dejado de asistir por un tiempo,
al igual que a todas las otras formas externas,
y que me mantenía retirado en mi aposento en los
días usualmente designados para ese propósito.
Cuando él oyó eso,
me preguntó si su compañía sería aceptable el siguiente día del Señor (como lo llamó él),
pues la adoración nacional no era agradable para él. Yo le di libertad,
y así él y su hijo llegaron a mi aposento, donde yo estaba sentado en silencio solo,
esperando en el Señor. Después de un cortés recibimiento y una breve pausa en silencio,
él empezó a magnificar la gran providencia de Dios por el
restablecimiento y progreso de los independientes y presbiterianos,
los cuales habían sido muy odiados, perseguidos y reprimidos,
pero que iban a ser hechos el instrumento principal de liberación,
restauración y reforma hacia la forma correcta del Señor y para Su propia gloria.
Mientras hablaba, observé que él mismo no estaba sobre el verdadero fundamento,
ni conocía la mente del Señor al respecto,
sino que hablaba desde su propia imaginación y parcialidad hacia su propia secta,
tal como él y ellos deseaban que fuera.
Su mente era natural y carnal,
y sus perspectivas eran externas y dirigidas hacia el poder y dominio de este mundo,
tal como los judíos en el momento de la aparición de Cristo entre ellos.

Tan pronto como hizo una pausa,
descubrí mi mente llena de la dulzura y mansedumbre de la verdad divina, y respondí:
"`La providencia divina es en verdad grande sobre los hijos de los hombres,
y aparentemente sobre esta nación y los que dependen de ella hoy.
Y en efecto, la necesidad de una correcta y completa reforma es muy grande,
y de seguro sucederá, en el tiempo y forma apropiados del Todopoderoso.
Pero no será ni por los medios ni por los instrumentos que
están ahora en tu opinión. Porque todos los contendientes,
que disputan unos contra otros, por una fuerza destructiva,
son de un espíritu dividido contra sí mismo, bajo diferentes formas y opiniones,
y los más fuertes avanzarán, ellos y su propia forma.
Pero estos no pueden, por tales medios, reformarse ni a sí mismos, ni a otros,
como deben hacerlo a los ojos de Dios, porque Él no aprueba ni tolera la violencia,
el derramamiento de sangre, ni la injusticia en una secta,
y luego condena las mismas cosas en otra.
Por tanto, el Señor llevará a cabo la reforma correcta,
mediante instrumentos de un tipo diferente, y por otros medios y formas,
como está escrito: '`No con ejército, ni con fuerza, sino con mi Espíritu,
ha dicho Jehová de los ejércitos.`'`" Ante esto,
el extranjero quedó muy quebrantado de espíritu,
y cuando se sentó a mi lado las lágrimas corrían por su barba y caían sobre su rodilla.
Entonces, lleno de amor (el mismo amor que lo había alcanzado desde mi espíritu),
me rodeó con sus brazos, regocijándose porque se había reunido conmigo,
pero no dijo nada más sobre algún tema religioso.
Poco después se fue y nunca lo volví a ver.

Ahora continúo con el relato de mi progreso.
Al escribir el último párrafo de un pieza,
el pueblo llamado '`cuáqueros`' fue repentinamente, y con cierta sorpresa,
traído a mi mente.
Quedó tan fuertemente impreso en mi memoria, que a partir de ese momento,
yo tenía una secreta inclinación a investigar más con respecto a ellos,
su forma y principios.
En algún momento del quinto mes de 1691 se presentó una oportunidad.
La ocasión tuvo lugar en la parte oeste de Cumberland,
cuando estaba alojado en una posada que era atendida por uno de esa profesión.
Cuando le pregunté al posadero sobre algunos puntos de la religión de ellos,
no percibí ninguna diferencia significativa entre sus opiniones y las mías. Él también
percibió que yo estaba más cerca de estar de acuerdo con ellos de lo que él,
o tal vez cualquier otro, hubiera pensado;
pues yo anteriormente me había opuesto al mismo hombre en algunas cosas.
Esto le dio la oportunidad de informarme de una reunión
que se iba a celebrar al día siguiente,
en un pueblo rural llamado Broughton.

Como yo deseaba estar informado correctamente sobre este pueblo,
y ver cómo eran realmente, me complació la oportunidad.
Así que la mañana siguiente el Amigo y yo nos dirigimos a la reunión. Él,
ansioso de yo estuviera más informado y convencido de la verdad del camino de ellos,
iba diciendo muchas cosas mientras cabalgábamos.
No dudo de que tenía buenas intenciones,
pero mi mente estaba serena y su atención dirigida hacia Dios (que
sabía que yo sólo quería ver la verdad y no ser engañado),
de modo que no podía tomar nota de lo que el Amigo decía. Al percibir esto,
después de un rato desistió y no dijo nada más,
y cabalgamos algunas millas en profundo silencio,
en el que mi mente disfrutó de un apacible descanso
y consolación de la divina y santa presencia.

Llegamos a la reunión un poco tarde, cuando ya estaba completamente reunida,
y pasé en medio de la multitud de personas en las bancas,
y me senté quieto entre ellos en una condición interna de retiro mental.
Uno de sus ministros, un extranjero,
empezó a declarar algunos puntos que ellos sostenían,
y a hablar contra algunas cosas que otros sostenían;
particularmente de la predestinación, tal como es afirmada por los presbiterianos.
Tomé poca nota de lo que era dicho, sin dudar de que, como todas las otras sectas,
estos tenían algo que decir, tanto de sus propios principios,
como en contra de las opiniones de otros.
En ese momento mi único interés era,
saber si ellos eran un pueblo que se congregaba bajo el vivo sentido
del deleite de la presencia de Dios en sus reuniones;
dicho en otras palabras,
saber si ellos adoraban al Dios verdadero y vivo en la vida y naturaleza de Cristo,
el Hijo de Dios, el verdadero y único Salvador.
El Señor respondió mi deseo según la integridad de mi corazón,
porque no mucho después de que me había sentado entre ellos,
esa nube celestial y cargada de agua dominó mi mente
e irrumpió en un dulce aguacero de lluvia celestial.
Entonces, la mayor parte de la asamblea fue quebrantada,
derretida y consolada en la divina presencia del verdadero Señor celestial,
lo cual se repitió varias veces antes de que finalizara la reunión. De esta misma manera,
y por el mismo poder divino,
a menudo había sido favorecido por el Señor cuando estaba solo,
cuando ningún ojo sino el del cielo me veía. Y entonces,
así como muchos manantiales y arroyos pequeños que descienden
en un solo lugar forman un río profundo y caudaloso,
así sentí un incremento en el gozo de la salvación de Dios,
mientras estaba reunido con el pueblo congregado por el Dios vivo,
en la experiencia de Su presencia divina y viva, a través de Jesucristo,
el Hijo de Dios y Salvador del mundo.
Mi gozo fue más pleno,
al reconocer que yo había estado bajo el mismo error del profeta de antaño,
pero entonces fui informado de lo contrario por una evidencia
segura y por el testimonio de la verdad divina,
en la que ningún alma viva puede errar o ser engañada,
al ser patente e innegable en todos los que verdaderamente lo conocen a Él.

Nuestro gozo era mutuo y pleno, eso sí, con muchas lágrimas,
como en los casos del amor más profundo y sincero.
Los Amigos ahí fueron conscientes de que yo estaba afectado y enternecido con ellos,
por la influencia de la verdad divina que ellos conocían y profesaban,
y concluyeron que había sido en ese momento, y no antes,
que fui convencido y llegué al conocimiento del camino de la verdad.
El gozo de ellos era como el gozo del cielo al regreso de un arrepentido,
y el mío era como el gozo de la salvación,
al ver la obra del Señor llevada tan lejos en la tierra,
cuando yo no mucho tiempo antes había
pensado que escasamente existía una fe verdadera y viva,
o conocimiento de Dios en el mundo.

Cuando terminó la reunión,
la paz de Dios que sobrepasa todo el entendimiento de los hombres naturales,
y que es inexplicable en cualquier idioma salvo, únicamente por sí misma,
permaneció sobre mi mente como un dosel santo,
en un silencio fuera del alcance de todas las palabras,
donde ninguna idea más que la Palabra misma puede ser concebida.
Fui invitado, junto con el Amigo ministro, a la casa de la anciana viuda Hall,
y de buena gana fui con ellos.
Sin embargo, permanecía dentro de mí un dulce silencio decretado, y por tanto,
no le dije nada a ninguno de ellos hasta que le plació
al Señor correr la cortina y velo de Su presencia.
Entonces descubrí mi mente pura y bajo una bien delimitada
libertad de inocente conversación con ellos.
Después de haber estado ahí por poco tiempo,
me invitaron a cenar en la casa de Richard Ribton,
un anciano y honorable Amigo en el pueblo,
donde fui amablemente recibido y donde tuve gran libertad de conversación.

En ese momento estaba satisfecho más allá de mis expectativas,
con respecto al verdadero pueblo de Dios,
en el que el Señor había comenzado (y en una buena
medida avanzaba) una gran obra y reforma en la tierra.
Entonces decidí dejar a un lado todos los asuntos y cosas que pudieran estorbar o velar
en mí el disfrute de la presencia del Señor (ya fuera entre Su pueblo o solo),
u obstruir cualquier servicio al que pudiera ser llamado por Él.
Deseché todas las cosas de naturaleza enredada o limitante,
independientemente de lo que el mundo dijera, o qué nombre me impusieran.

Cuando terminé con el asunto que me había llevado a esa parte del país,
regresé a Carlisle.
Después de esto asistí a algunas otras reuniones de Amigos,
pero ninguno de mis parientes o conocidos lo notó,
hasta el momento de las sesiones de la corte en Carlisle,
donde algunos Amigos estaban prisioneros en la cárcel del condado por no pagar los diezmos.
Varios otros Amigos asistían a estas sesiones (como era su costumbre)
para ayudar a prevenir problemas o daños a alguno de la Sociedad,
y ministrar consejo u otra ayuda según fuera necesario.
Estos Amigos se unieron para hacer una reunión en Scotby,
aproximadamente a dos millas de la ciudad, y yo también fui.
Durante el tiempo de la reunión encontré una carga inusual sobre mi espíritu,
y tal dureza en mi corazón que apenas podía respirar bajo la opresión.
No podía sentir los consuelos de la presencia divina,
sino que los cielos eran como bronce grueso y sus barrotes como hierro fuerte.
Pero aunque yo no experimentaba disfrute,
era consciente de que la presencia y bondad del Señor estaban ahí,
y de que muchos eran enormemente consolados.
Por tanto,
llegué a la conclusión de que la condición de mi mente era por alguna otra causa,
y que no estaba relacionada con el estado de la reunión en general.

Después de que terminó la reunión, uno de ellos me preguntó cómo estaba.
Yo le respondí tibiamente,
así que él y algunos otros percibieron que mi espíritu estaba oprimido,
y se compadecieron de mí. En todo ese tiempo no pude descubrir
el asunto en particular que me afectaba de esa manera,
porque no sabía de nada que hubiera hecho o dicho
que trajera eso sobre mí. Pero esa tarde,
al regresar a la casa de mi padre muy solitario, en silencio y ensimismado,
llegó un tal Thomas Tod, que deseaba hablar conmigo.
Me dijo que tenía un juicio al día siguiente sobre
ciertas casas de su propiedad en el pueblo de Penrith,
las cuales constituían la mayor parte de todo lo que tenía en el mundo.
Uno de los testigos de la escritura de compraventa estaba muerto,
otro se había ido a Irlanda, y esperaba que yo, siendo el tercero,
y el que había preparado los documentos, lo ayudara contra su adversario injusto.
Él deseaba que yo estuviera listo en la mañana,
porque el juicio probablemente comenzaría muy temprano.

Tan pronto como él comenzó el relato,
también comenzó a obrar la Palabra de vida en mí de manera poderosa.
Yo sentía palpablemente el martillo del Señor,
y vi que era levantado contra esa dureza de corazón
que por algún tiempo había sido mi estado.
Mi corazón empezó a quebrarse, suavizarse y disolverse,
y la consciencia del amor de Dios fue renovada en algún grado.
Entonces claramente vi que eso era lo que tenía que atravesar,
y que ese era el tiempo de prueba en el que debía tomar la cruz de Cristo,
y confesar Su doctrina en este punto plena y abiertamente,
según el entendimiento que me había sido dado.
Vi que debía despreciar la vergüenza,
el oprobio y cualquier sufrimiento (lo cual yo sabía bien que sucedería rápidamente),
o debía dejar al Señor para siempre.
Porque si negaba Su doctrina,
después de haber recibido un sentido tan claro y simple de ella,
sería una negación de Él delante de los hombres.
Y si lo negaba a Él,
no podía esperar menos (según Su palabra) que ser
negado por Él inmediatamente y para siempre,
y dejado bajo esa dureza de corazón y falta de disfrute de Su divina presencia,
con la que había sido favorecido antes.
Pero, debido a los avances de Su Palabra y de Su obra en mí en ese momento,
mi corazón se inclinó hacia Él. Y para cuando mi conocido terminó de hablar,
estaba plenamente determinado a darle la siguiente respuesta clara y directa:
"`Estoy verdaderamente dispuesto, y compareceré y testificaré lo que sé de este asunto,
y haré lo que pueda por ti en ese sentido,
pero no juraré.`" Esto fue una gran sorpresa para él,
tanto por la naturaleza de su caso como por la confianza que tenía de mi pronta
anuencia (ya que no tenía sospecha de mi condición hasta ese momento),
de modo que estalló en cólera y con una maldición dijo: "`¡Qué,
de seguro que no eres un cuáquero!`"
A pesar de que la divina presencia había regresado manifiestamente en mí,
ante esta pregunta volví a guardar silencio,
hasta que tuve claro en mi entendimiento qué responder con sinceridad y verdad.
Dado que nadie antes de ese momento me había llamado cuáquero,
yo no había asumido aún el nombre, ni tampoco sabía entonces,
si yo tenía completa unidad con todos los principios,
lo que habría justificado que yo llevara el nombre,
pues yo los había conocido únicamente en la unidad del amor y vida divinos,
y aún no había escuchado todas sus doctrinas;
pero el poder de la Vida que prohíbe todo juramento,
se levantó más claro y completo en mí. El Señor abrió mi entendimiento,
aclaró mi camino y me facultó para responder: "`Debo confesar la verdad:
Soy un cuáquero.`"

Así como esa confesión me acercó aún más al Hijo de Dios,
de modo que sentía que Su amor se incrementaba en mí,
de igual manera aumentó la perplejidad y perturbación de mi amigo, cuyo caso,
en su opinión, se volvió más desesperado como resultado de mi declaración. Ante esto,
en un incremento de tensión y de expresiones que se ajustaban a su evidente decepción,
luego me amenazó con acusarme con la corte para que me multara
y procediera contra mí con el mayor rigor de la ley.
"`¡Qué!,`" dijo él,
"`¿debo perder mi patrimonio debido a tus conceptos y caprichos infundados?`"
Pero cuanto más alto se alzaba y enfurecía mi enemigo en
este bien intencionado pero equivocado hombre (quien,
sin intención, se había convertido en el instrumento de mi prueba),
más completo y más poderoso era el amor de Dios en mí,
cuya causa yo había defendido a través de Su propia ayuda y del poder
de una vida indestructible manifestada en mí. Yo respondí en esa tranquila
rendición a la voluntad de Dios que la vida del Hijo de Dios enseña,
y en la que faculta actuar: "`Tú puedes hacer lo que creas apropiado,
pero yo no puedo cumplir con tu pedido en este asunto,
cualquiera que sea la consecuencia.`"
Entonces él se fue con una gran insatisfacción,
y con todas las amenazas y reproches que sus pasiones enfurecidas podían sugerir,
ante la perspectiva de una gran pérdida.

Yo me retiré inmediatamente a mi aposento,
porque percibí que mi gran enemigo todavía estaba obrando para introducir un temor servil,
y por ese medio someter mi mente y llevarme de nuevo al cautiverio y a la esclavitud.
Yo deseaba estar solo y libre de las interrupciones de otros,
para poder experimentar más plenamente el brazo del Señor
y Sus instrucciones y consejos divinos en este gran ejercicio.
El enemigo, al ser un astuto y sutil espíritu,
obró sobre esas pasiones que no estaban completamente sujetas,
e ingeniosamente se dedicó a mi razón y entendimiento naturales,
los cuales no estaban enteramente iluminados.
Insistía en la multa y el encarcelamiento,
las dificultades que acompañarían esta condición,
y la poca ayuda que podría esperar de mi padre y amigos,
quienes se disgustarían mucho conmigo por una resolución tan tonta e inexplicable,
tal como ellos la verían. También apuntaba la burla, el escarnio, mofa, desdén,
desprecio, pérdida de amigos y amistades en el mundo,
junto con otros inconvenientes y dificultades similares, y malas consecuencias.
Durante todo ese tiempo, desde aproximadamente las ocho de la noche hasta la medianoche,
el ojo de mi mente se mantuvo fijo en el amor de Dios,
el cual todavía era palpable en mí, y mi alma se adhirió a él con gran sencillez,
humildad y confianza, sin cederle a Satanás ni a sus razonamientos en estos temas,
donde '`carne y sangre`' en su propia fuerza es fácilmente
vencida por él. Pero alrededor de las doce de la noche,
el Señor lo silenció por completo, junto con todas su tentaciones,
y solo la vida del Hijo de Dios quedó en mi alma.
Luego, desde la consciencia de Su maravillosa obra y brazo redentor,
se levantó en mi con poder el dicho del apóstol:
"`La ley del Espíritu de vida en Cristo Jesús me ha librado de la ley del pecado y muerte.`"
Entonces las enseñanzas del Señor fueron abundantes y gloriosas,
y mi entendimiento fue más despejado.
Su santa ley de amor y vida se estableció en mí,
fui aceptado en el dulce reposo con el Señor mi Salvador,
y entregado en perfecta rendición a Su santa voluntad,
en todo lo que se relacionara con esta gran prueba de mi fe y obediencia al Señor.

En la mañana fui a la sala donde se sientan los jueces,
esperando ser llamado como testigo en el caso antes mencionado.
Pero antes de llegar al lugar, vi que mi conocido se me acercaba,
con un aire en su semblante que denotaba amistad y afecto.
Cuando nos encontramos me dijo: "`¡Puedo darte buenas noticias!
Mi adversario ha dejado la causa y llegamos a un acuerdo para mi
satisfacción.`" Al escuchar esto me quedé quieto en la calle,
y mientras repasaba en mi mente la obra del Señor
en mí la noche anterior (como ya la relaté),
esta Escritura vino fresca y vívidamente a mi memoria:
"`Porque Dios es el que en vosotros produce así el querer como el hacer,
por su buena voluntad.`"
Estaba consciente de que había sido '`el hacer`' del Señor
y lo consideré una gran misericordia y liberación.

Sin embargo, por ese medio quedé expuesto a la vista y observación de todos,
a la lástima de muchos y a las burlas y censuras del tipo más bajo e ignorante.
Este hecho sucedió en el momento de las sesiones de la corte,
cuando había ahí personas de todos los sectores,
y rápidamente me convertí en tema de conversación y debate.
Pocos podían creer la noticia de que yo era ahora un cuáquero, y muchos iban a ver,
hablar y mofarse.
Cuando por casualidad me veían a lo lejos en las calles, venían en multitudes para mirar.
Algunos se quitaban sus sombreros y fingían mostrar más que cortesía ordinaria,
saludándome como en otros tiempos, pero como yo no les respondía de la misma manera,
algunos sonreían con superioridad, se reían, se burlaban,
hacían muecas y se alejaban riendo a carcajadas diciendo que yo estaba loco.
Otros reaccionaban poniéndose pálidos, parecían tristes y regresaban llorando.
Uno que había sido educado en una universidad, para mostrar su temperamento,
modales y aprendizaje a la vez,
después de que me había mirado un rato con muchos otros del tipo más bajo, exclamó:
"`¡Él no sabe distinguir entre un género y una especie!,`" cuando
no había nada previo que condujera a tal expresión. Sin embargo,
estaba equivocado en eso, porque yo sabía muy bien que el perro es un género,
y que un buldog y un sabueso son especies distintas de ese género.
Y en ese momento vi que la naturaleza y forma de esos animales,
aparecía en esa multitud atolondrada, aunque no dije mucho a ninguno de ellos,
y los dejé que me miraran a la cara y que se rieran tanto como quisieran.

Algunos, que uno o dos días antes no se hubieran atrevido a mirarme de manera descortés,
en ese momento me insultaban y se regocijaban.
Esto trajo a mi mente el decir de Job: "`Pero ahora se ríen de mí los más jóvenes que yo,
a cuyos padres yo desdeñara poner con los perros de mi ganado.`"
A pesar de eso, la pretendida compasión e instrucción del tonto,
que no podía ver ni compadecerse de su propia condición miserable,
era los más difícil de soportar.
Sin embargo, ninguna de esas cosas me provocaba ni me conmovía,
porque la gracia y presencia del Señor estaban sobre mí,
y eran mi fortaleza y preservación. En realidad,
mi corazón estaba rodeado con una muralla de paciencia invencible,
y mi alma estaba llena de amor divino.
Ese trato me dio una visión más clara del estado bajo, malo,
miserable y brutal de muchos hombres, de la que había tenido antes,
o habría podido imaginar.

Cuando el asunto de las sesiones de la corte se terminó,
algunos de mis conocidos (caballeros tanto de la ciudad como del campo,
que me deseaban el bien a su manera), pensando que los cuáqueros me habían engañado,
consultaban cómo restaurarme y recuperarme (aunque no creo que alguno
de ellos supiera qué eran los verdaderos cuáqueros y sus principios).
Se propusieron varias maneras para ayudarme, especialmente,
mediante una reunión y consulta con algunos de los clérigos, quienes, según ellos,
podrían resolver cualquier duda que tuviera,
al suponer que mis opiniones habían sido recientemente adoptadas,
y que yo no me había establecido aún en ellas.
En general, los clérigos me rechazaron,
y rápidamente observé una particular enemistad en ellos contra mí,
aunque yo no les tenía más aversión que a otros.
Sin embargo, algunos de los interesados en mí arriba mencionados,
habiendo visto mi anterior frivolidad y alegría convertidas en silencio y seriedad,
supusieron que estaba melancólico.
Estos se reunieron en una taberna, junto con mi padre,
con el deseo de hacerme beber un fuerte trago,
buscando levantar mi espíritu a un temperamento más sociable y rescatarme de tales ideas.

Mientras ellos tramaban ese plan,
yo estaba retirado en mi habitación solo y favorecido con una sensación
de la buena y nutritiva presencia del Señor. Pero después de un rato,
vino sobre mí una preocupación que me hizo suponer
que algo con respecto a mí estaba en movimiento.
Poco después, un conocido que era abogado,
vino a mí desde la reunión y mencionó a ciertos caballeros
que deseaban verme en la taberna.
Yo no me apresuré a ir ni me rehusé, sino que busqué el rostro del Señor en ese asunto.
Después de un corto tiempo,
mi padre y algunos otros se impacientaron porque querían que yo estuviera con ellos,
y también llegaron a verme.
Yo me levanté de mi asiento cuando entraron, pero no me quité el sombrero ante ellos,
como lo hicieron ellos ante mí,
por lo que mi padre se echó a llorar y dijo que yo no solía
comportarme así con él. Le supliqué que no lo tomara a mal,
como si fuera una falta,
porque aunque yo en ese momento pensaba apropiado declinar esa ceremonia,
no eran por desobediencia o por falta de respeto hacia él,
porque yo lo honraba tanto como siempre,
y deseaba que a él le placiera pensar que así era.
A través de la gracia, me percaté de las intenciones de ellos,
pero pronto encontré libertad en mi mente para ir con ellos.

Cuando llegamos a la taberna, me colocaron de manera que yo quedara en medio de ellos,
y luego pusieron la copa para que circulara alrededor de la mesa;
y a fin de disfrutarla aún más, propusieron beber a la salud del rey Guillermo.
La copa avanzó hasta que llegó a mí,
y entonces les dije que yo deseaba el bien tanto para el rey como para ellos,
y que si yo podía beber a la salud de alguno, lo haría especialmente por la del rey,
pero que ya no haría más esas cosas; y así lo rechacé. La copa no dio la vuelta,
pues varios de ellos lloraban y estaban muy quebrantados,
y todos se quedaron en silencio por un rato.
Cuando pasó, algunos dijeron que creían que yo tenía buenas intenciones en lo que hacía,
y que cada hombre debía ser dejado para que procediera en
la forma que pensaba correcta ante los ojos de Dios.
Y así, nos separamos en sólida amistad.

La gracia secreta de Dios fue la que obró esto, y a Él, y sólo al Señor,
lo atribuí. He tenido muchas disputas con muchas personas desde entonces,
y en varias partes del mundo, pero nunca he comenzado una discusión,
al estar siempre en el lado que se defiende.
Y raramente entraba en un debate sobre algún punto en particular,
con algún hombre o secta,
hasta que sentía que la verdad divina se levantaba sobre todo en mi propia mente,
y mi voluntad era sujetada por ella.
Mi siguiente objetivo era generalmente, no provocar a mi oponente,
porque al mantenerlo calmado, tanto su propio entendimiento,
como la medida de gracia que estaba en él,
obraban contra el error por el que contendía. Pues cuando el hombre se apasiona,
puede ser confundido, pero no convencido.
La pasión es como un fuego abrazador sin luz.
Detiene el entendimiento y obstruye el camino hacia este,
de modo que no puede ser alcanzado ni informado.
Por tanto, mi principal objetivo en las disputas de asuntos de religión ha sido,
alcanzar el entendimiento de las personas para su propio bien, o de lo contrario,
todo terminará en vana e infructuosa palabrería, lo cual, desagrada al Santo.
En dos o tres ocasiones en el curso de mi vida,
en acciones demasiado apresuradas en mi propia fuerza, mi mente se ha alterado,
y aunque he ganado el punto por la fuerza de la razón (sólo por
el principio de la razón y no por el principio de la Verdad divina),
no he tenido esa paz y satisfacción de mente que
sólo se encuentran en la virtud de la verdad.
Eso también me ha enseñado a mantenerme totalmente callado,
y a veces incluso insultado por personas ignorantes, como si no tuviera nada que decir,
hasta que el poder y la virtud de la verdad se levanten en mi mente.
Pero cuando se levantan, nunca han fallado en apoyar su propia causa,
mediante su propia luz y evidencia.

En todo ese tiempo yo no había conversado con ningún Amigo acerca de sus principios,
o leído alguno de sus libros,
ni ninguno de ellos se había acercado a mí por algún tiempo,
porque mi padre no les permitía ir a su casa.
Algunos de ellos, no mucho después, me enviaron tres pequeños libros,
que tomé amablemente, sabiendo que tenían buenas intenciones.
Pero fui favorecido por el Señor con algo más excelente que libros,
que me dio entendimiento y apoyo en momentos de necesidad.
En efecto, ese libro, que había sido sellado con siete sellos, fue entonces,
en alguna medida, abierto por la poderosa voz del León de la tribu real,
el Cordero Santo de Dios (es decir, el libro de la ley eterna de Dios,
la ley del Espíritu de vida del Padre), por Cristo el Hijo, el Redentor del mundo,
y fue mi deleite leerlo día y noche.
Por medio de esto obtuve más beneficio en el conocimiento
de Dios y las cosas de Su santo reino en corto tiempo,
que si hubiera leído y entendido todos los escritos y libros impresos en el mundo.
Por tanto, decliné leer los libros de los Amigos hasta una época más apropiada,
y después escudriñé uno de los libros sobre la oración. Ciertamente,
leer buenos libros (especialmente las Sagradas Escrituras,
el principal de todos) es altamente beneficioso y recomendable.

Yo iba constantemente a las reuniones de Amigos, donde, en estado de silencio,
mi corazón era frecuentemente enternecido y quebrantado
por la influencia divina de la verdad,
para mi indecible satisfacción. Allí encontraba un
placer y disfrute santo que ni el mundo,
ni nada en él, podía ofrecer.
Nuestras reuniones en el norte en aquellos días eran a menudo
quebrantadas y derretidas cuando estaban en silencio,
como también cuando estaban bajo el ministerio poderoso y vivo de la Palabra.
Mi deleite estaba continuamente en la verdad,
y no deseaba ninguna compañía sino la de los Amigos.
Yo frecuentaba las reuniones en todas las ocasiones,
donde mi corazón a menudo estaba tan enternecido por la verdad,
que esta alcanzaba y afectaba a los otros a través mío. De esta
manera llegué a ser muy querido por los Amigos y ellos para mí.
Y como esta ternura era algo así como un ministerio involuntario,
al ser operación del Espíritu de Dios sin palabras,
por un tiempo encontré gran satisfacción y seguridad en este.

Como deseaba ver Amigos en otros lugares, hice un corto viaje con Andrew Taylor,
un ministro poderoso y capaz en su día, de carácter afable y alegre,
y uno de mis amigos en especial.
El 20 del mes doce de 1691, fuimos a Heatherside, en Cumberland,
y esa noche nos alojamos a dos millas más allá de Alston.
El siguiente día viajamos a Welgill, el 22 a la casa de Thomas Williamson,
el 23 a Walkmill, el 24 a Steel y el 25 a Benfieldside;
teniendo reuniones en varios de esos lugares.
De ahí nos fuimos el 27 a Newcastle y nos alojamos en la casa de Jeremías Hunter,
y estuvimos en la reunión de ellos al día siguiente.
El 29 fuimos a la casa de Caleb Tenent en Shields y tuvimos
una reunión allí. El primer día del primer mes,
se fijó una reunión en Sunderland.
Nosotros teníamos la intención de cruzar el Río Tyne en Shields a fin de asistir,
pero como el viento era muy fuerte,
los caballos estaban asustados con el revoloteo de las velas mientras salíamos del cayo,
de modo que la yegua de Caleb, que era fuerte y vivaz,
saltó sobre la borda y se lo llevó con ella cuando él luchaba por detenerla por la brida.
Ambos se sumergieron bajo el agua, pues ahí era muy profunda,
pero como la buena Providencia quería,
la yegua emergió con su cabeza hacia la orilla y Caleb apareció
detrás de ella a tan poca distancia y con tanta presencia de ánimo,
que se agarró de la cola y llegó a la orilla sin
más daño que la sorpresa y la ropa mojada.

La reunión en Sunderland resultó ser un tiempo de mucho
consuelo en el disfrute de la buena presencia del Señor,
con la que mi corazón fue abundantemente suplido.
En el tiempo de silencio fui enormemente enternecido,
y muy pronto estaba bañado en un mar de lágrimas
por la experiencia del divino amor que derrite;
y el mismo efecto se vio sobre toda la reunión. Después de eso, Robert Wardel,
un Amigo ministro en cuya casa estábamos alojados, dijo algunas frases,
por las que percibí que él pensaba que yo debía pronunciar
en ese momento algunas palabras a manera de ministerio público.
Pero yo no creía que mi tiempo había llegado para ese servicio, y además,
la ministración de la Palabra, mediante una operación más directa,
había tenido el mismo efecto, o tal vez más grande,
que la pronunciación de muchas palabras.

Después de la reunión muchos Amigos se me acercaron y me expresaron tanto amor y respeto,
que me dio motivo para considerar cual podría ser la razón,
pues todos ellos eran extraños para mí y yo para ellos.
Al no ser más que un niño en el conocimiento de la operación invisible
de la Palabra de verdad y sus efectos por medio de instrumentos,
incluso en la forma de silencio y solidaridad,
yo sólo había visto sus efectos en mí mismo,
y para mi propia fortaleza y consolación. Yo no sabía aún,
que cuando la verdad irrumpía sobre uno de manera eminente,
a menudo afectaba la parte viva de la reunión, de la misma manera y al mismo tiempo.
Desde entonces, ha llegado a ser claro para mi entendimiento, por experiencia,
que hay una comunicación indescriptible del divino amor
a través del único Espíritu entre los santificados en Cristo,
cuando los miembros de Cristo se sientan juntos en un estado
de silencio santo en sus lugares celestiales en Él.

[.asterism]
'''

__Thomas Story se convirtió en un ministro extremadamente
dotado y servicial en la Sociedad de Amigos,
que viajó por todo Inglaterra, Irlanda, Escocia, Holanda, Jamaica,
Barbados y las colonias en América.
Fue conocido tanto por su profundidad espiritual como por su genio intelectual,
y sus escritos llegaron a ser de mucha influencia entre los cuáqueros.__

__En 1695 Thomas Story se hizo amigo de William Penn,
y en 1698 navegó a Pensilvania (a pedido de Penn),
donde ocupó varios cargos públicos en la provincia en desarrollo.
Permaneció ahí por dieciséis años,
y siempre puso las tareas ministeriales en el cuerpo
de Señor por encima de sus negocios en el mundo,
e incluso,
declinó posiciones y promociones que podrían haber estorbado su servicio a la iglesia.
Se casó en América, pero perdió su esposa después de sólo seis años,
y luego regresó a Inglaterra donde continuó como ministro hasta su muerte en 1742.__
